### ISSUE TITLE
BUG/ISSUE -- Inaccurate keying/numbering @ Kanji Search Filters

### ISSUE THREAD

**Issue by am2del** [z1dev/zkanji#19]
When taking at look at `Kanji search -> Filters`, no. `3` is missing and there are TWO of no. `5` - thus making keys `3` and `5` disfunctional when using shortcuts to show/hide filters at the "Kanji Search"-widget.

As a result, key no. `4` leads to "Meaning" _(which is no. `3` if clicking filter-buttons)_.

"Reading" as well as "Jyouyou" cannot be triggerd by shortcut at all.

**Comment by z1dev** [comment]
The bug was caused when I moved the `JLPT` field to be after `Strokes` for better use of space, and didn't correctly change the shortcuts at one place. It's fixed but please check it first before I close this issue.
