### ISSUE TITLE
Examples not shown in word group.

### ISSUE THREAD

**Issue by ambujp** [z1dev/zkanji#26]
> Who :

 User

> What :

 Allows user to see the example sentences in word group.

> Why : 

 Currently use is able to see example sentences in "**Dictionary Search**" view. However, when same word is added in **"**Word Group**"** he cant see example sentences. 
Not sure if there is any setting to enable it, which i couldn't find. Please consider and decide the priority.
This allows users effort during revision.

**Comment by z1dev** [comment]
I'll consider this but it needs some work.

**Comment by z1dev** [comment]
Word examples should show up in word group from the next version, but I had to prevent interaction with the examples text so the user won't be able to change which word is shown in the examples for the group widget.
