### ISSUE TITLE
crash when adding a word and there's no study deck created yet.

### ISSUE THREAD

**Issue by gyan000** [z1dev/zkanji#4]
Hello,

All is almost explained in the subject issue.

**How to reproduce**
dictionary search mode -> search a kanji -> in the list view result, right-click -> "Add word to study deck" 

I don't know what is the best option here :
* Create a default study deck when we select the option "Add word to study deck".
* Or a popup warning, asking to user to create a study deck.
* Or create a default study deck at startup if there's no one.
* Or display the study deck configuration window (perhaps the best here)

**Logs**
[qtcreator_debugger.txt](https://github.com/z1dev/zkanji/files/1210593/qtcreator_debugger.txt)
[backtrace.txt](https://github.com/z1dev/zkanji/files/1210594/backtrace.txt)

note : zkanji v0.0.3-alpha (fedora 26)

Thanks

**Comment by z1dev** [comment]
Thanks for reporting that.

I think I'll go with the automatic deck creation when the user tries to add words to decks. That sounds the most natural.

**Comment by z1dev** [comment]
A new deck called "Deck 1" is now created when trying to study with a deck and there's no deck in the dictionary.

**Comment by gyan000** [comment]
Working as expected, thanks.
