### ISSUE TITLE
somehow creating a new dictionary will not work

### ISSUE THREAD

**Issue by petKitsune** [z1dev/zkanji#5]
Zkanji V 0.0.0.3 portable
win7x64

it's possible that I don't understand this function correctly
don't shoot when I'm wrong
I'm just trying to be a friendly domesticated fox

Menu > Dictonary > Manage Dictionary > Create new > Enter name > click ok
works fine
select new dic
works fine
Menu > Dictionary search > New word to dictionary > bla bla bla > save
works fine
Restart Zkanji
New dictionary is gone
editing the states.xml directly [who knows] does not do the trick

tried al lot
looks like the program got a short term memory lost
it will not save the new dic
or it doesn't know how yet

[EDIT: some info]

**Comment by z1dev** [comment]
Thanks, I'll look into this. The program should save dictionaries. I must have forgot to tell the program that the dictionary is changed when you add a new word (unchanged dictionaries are not saved) or quitting just doesn't give enough time for the save.

**Comment by z1dev** [comment]
I have fixed it so I'm closing this issue. It'll be good in the next release. (Hopefully)

**Comment by petKitsune** [comment]
nice
big thx
