### ISSUE TITLE
No go on the Interface scaling

### ISSUE THREAD

**Issue by petKitsune** [z1dev/zkanji#6]
Zkanji V 0.0.0.3 portable
win7x64

Menu > File > Settings > Appearance > Interface scaling > Restart
Menu > File > Settings > Appearance > Interface scaling > Restart
Menu > File > Settings > Appearance .... 

the setting is back to default after restart

**Comment by z1dev** [comment]
Interface scaling is not yet implemented. I wrote a bit about that in this [blog post](https://zkanji.wordpress.com/2017/07/26/zkanji-test-v1/). I'm not yet sure how this will be done. I only plan to do it after the main bugs are fixed.

**Comment by petKitsune** [comment]
it's not a really important part
so take your time

**Comment by z1dev** [comment]
Interface scaling is now working more or less and will be in the next release, so I'll close this issue. If any problems come up please make another one.
