### ISSUE TITLE
Radical filter not working correctly ?

### ISSUE THREAD

**Issue by galtgendo** [z1dev/zkanji#7]
Unless I'm missing something, the reasonable way would be that the radical filter is an AND filter (kanji contains ALL of the radicals/parts). But - unless I'm missing something, it's currently an OR filter (kanji contains ANY of the radicals/parts).

...???

**Comment by z1dev** [comment]
In the previous versions it worked like that. In this version press "Add" (the button to the right) to start a new group. Radicals inside a single group are checked with OR while the groups themselves are checked with AND. I'm undecided whether this should be the final design or not, but it will be reasonably fast with a shortcut key for the "Add" button.

**Comment by z1dev** [comment]
I will close this issue because I'm cleaning up the issues list. I still haven't decided how this should work in the final version but I'll keep it the way it is for now.
